/* The Ledger — the About page.
   Shared by the app (index.html shows it in the reader, as a card at the foot of
   the front page) and the build (build.mjs writes it as /about/). It is part of
   the app, not an article: it carries no date and takes no place in the
   chronology. Everything here is a description of how the publication works,
   drawn from README.md and REVIEW.md; nothing about people or credentials that
   the publication has not stated. */
window.LEDGER_ABOUT = {
  title: "About The Ledger: a quiet place to read the market, one story at a time",
  standfirst: "What The Ledger is, how its own reporting is labelled, where the Newsstand comes from, and how to reach the desk. This page is part of the app, not an article, and carries no date.",
  html: `<p>The Ledger does one thing: it puts financial journalism in front of you without clutter. There are no adverts, no pop-ups asking for your email, and nothing here reaches past a publisher's paywall.</p>
  <h2>What The Ledger writes</h2>
  <p>The front page and the topic pages carry only The Ledger's own journalism: complete pieces written in The Ledger's own voice from credited research, not summaries of someone else's story. Every material source behind a piece is credited and linked in the <em>Sources &amp; further reading</em> box at its foot. Each piece has an address of its own, and its date is the date it was published; a news story more than a week old is marked <em>From the archive</em>.</p>
  <p>Each piece also carries a production label, and this is the standard The Ledger publishes to. <strong>Reported and written by The Ledger</strong> is meant to say that a person wrote the piece from the credited sources; <strong>Drafted with AI assistance</strong> that a model drafted it from the credited sources and a person checked every claim against them before publication. The label is set per piece in the publication's source, and the review process is written down there. The pieces published so far carry the default label and predate any kept review record, so the label describes the intended editorial standard rather than a completed, recorded review; a review record, where one exists, is in the repository's history for that piece.</p>
  <h2>The Newsstand</h2>
  <p>The Newsstand is a separate, labelled view: what the desk is reading from public feeds. The target is a fresh gathering every half hour, but the scheduled runs that do it are sometimes delayed by hours, so the view shows the time the edition was actually gathered and how long ago that was, and a refresh says in words whether a newer edition arrived. A third-party story appears there only as a brief summary with attribution and a link to the original, never as a Ledger article. Full text renders only under an explicit reuse licence, and that licence is named beside the piece. The context box on a Newsstand story is labelled honestly: <em>Background</em> is the desk's standing note on that kind of story; <em>Why it matters</em> appears only for a note an editor wrote about that particular story and checked against the sources it names.</p>
  <h2>Listening and copying</h2>
  <p>The headphone button reads a piece aloud. With your own OpenAI API key, entered in Settings and kept only on your device, it uses OpenAI's speech models; without one it falls back to the voice built into your phone, so the button always works. The copy button puts the whole piece on your clipboard as plain text: headline, publication, author, date, the original link, then the body.</p>
  <h2>Corrections and contact</h2>
  <p>The Ledger is published at readtheledger.github.io and its source, including every article, is public. To report an error, ask for a correction or write to the desk, open an issue on the repository: <a href="https://github.com/readtheledger/readtheledger.github.io/issues" target="_blank" rel="noopener noreferrer">github.com/readtheledger/readtheledger.github.io/issues</a>. A correction is made to the piece itself, at its own address.</p>
  <h2>What leaves your device</h2>
  <p>Saved stories, settings and any API key stay in this browser. What the app sends, and to whom: a page-view count for each page you open goes to GoatCounter, which sets no cookies; the gathered Newsstand edition is fetched from this site, and if that file cannot be read the app fetches the publishers' feeds through public relay services (allorigins.win, corsproxy.io, codetabs.com), which see the feed addresses requested; with an OpenAI API key entered, the text of a piece you listen to is sent to OpenAI to make the audio, and without one nothing is sent because the device's own voice reads it; a link out goes to the publisher, as any link does. The page's content security policy allows no other destinations. There is no advertising and no other analytics.</p>`
};
