/* The Ledger — the About page.
   Shared by the app (index.html shows it in the reader, as a card at the foot of
   the front page) and the build (build.mjs writes it as /about/). It is part of
   the app, not an article: it carries no date and takes no place in the
   chronology. Everything here is a description of how the publication works,
   drawn from README.md and REVIEW.md; nothing about people or credentials that
   the publication has not stated. */
window.LEDGER_ABOUT = {
  title: "About The Ledger: a quiet place to read the market, one story at a time",
  standfirst: "What The Ledger is, how its own reporting is labelled, where the Newsstand comes from, and how to reach the desk. This page is part of the app, not an article, and carries no date.",
  html: `<p>The Ledger does one thing: it puts financial journalism in front of you without clutter. There are no adverts, no pop-ups asking for your email, and nothing here reaches past a publisher's paywall.</p>
  <h2>What The Ledger writes</h2>
  <p>The front page and the topic pages carry only The Ledger's own journalism: complete pieces written in The Ledger's own voice from credited research, not summaries of someone else's story. Every material source behind a piece is credited and linked in the <em>Sources &amp; further reading</em> box at its foot. Each piece has an address of its own, and its date is the date it was published; a news story more than a week old is marked <em>From the archive</em>.</p>
  <p>Each piece carries an explicit attribution label. <strong>Reported and written by The Ledger</strong> means a person wrote it from the credited sources. <strong>Drafted with AI assistance</strong> means a model drafted it from the credited sources and a person checked every claim against them before publication. New pieces in either category must pass the same factual-source and read-aloud checklist; the publication pull request records that review. A label alone does not prove a review happened.</p>
  <p>The eight original articles published on August 17, 2026 carry a separate archive status: <strong>From The Ledger archive. A factual review record is not available for this article.</strong> Their historical production evidence is incomplete, so we do not claim that they were human-written or that a completed factual review is documented. A missing record does not establish that nobody reviewed them or that every article is inaccurate. This status is limited to those existing archive articles; new pieces and substantive revisions must follow the recorded review process. Their original publication dates are preserved.</p>
  <h2>The Newsstand</h2>
  <p>The Newsstand is a separate, labelled view: what the desk is reading from public feeds. The target is a fresh gathering every half hour, but the scheduled runs that do it are sometimes delayed by hours, so the view shows the time the edition was actually gathered and how long ago that was, and a refresh says in words whether a newer edition arrived. A third-party story appears there only as a brief summary with attribution and a link to the original, never as a Ledger article. Full text renders only under an explicit reuse licence, and that licence is named beside the piece. The context box on a Newsstand story is labelled honestly: <em>Background</em> is the desk's standing note on that kind of story; <em>Why it matters</em> appears only for a note an editor wrote about that particular story and checked against the sources it names.</p>
  <h2>Listening and copying</h2>
  <p>The headphone button reads a piece aloud. With your own OpenAI API key, entered in Settings and kept only on your device, it uses OpenAI's speech models; without one it falls back to the voice built into your phone, so the button always works. The copy button puts the whole piece on your clipboard as plain text: headline, publication, author, date, the original link, then the body.</p>
  <h2>Corrections and contact</h2>
  <p>The Ledger is published at readtheledger.github.io and its source, including every article, is public. To report an error, ask for a correction or write to the desk, open an issue on the repository: <a href="https://github.com/readtheledger/readtheledger.github.io/issues" target="_blank" rel="noopener noreferrer">github.com/readtheledger/readtheledger.github.io/issues</a>. A correction is made to the piece itself, at its own address.</p>
  <h2>What leaves your device</h2>
  <p>Saved stories and settings are stored locally, in this browser. An OpenAI API key, if you enter one, is stored locally too and is sent to OpenAI only when you use the optional authenticated speech: then the key and the text of the piece you are listening to go to OpenAI to make the audio. Without a key, Listen uses the browser's or device's own speech voice; whether that runs on the device or through the vendor's service depends on the browser and the voice chosen. Beyond that, the app requests: the typefaces, from Google Fonts; the gathered Newsstand edition, from this site, and if that file cannot be read, the publishers' feeds through public relay services (allorigins.win, corsproxy.io, codetabs.com), which see the feed addresses requested; and, in a Newsstand item that carries images, those images from the publisher's or its image host's servers. A link out goes to the publisher, as any link does. There is no advertising. On the public site, Cloudflare also receives the aggregate analytics described below.</p>
  <h2>Pageview counting and your choice</h2>
  <p>The public site uses <a href="https://developers.cloudflare.com/web-analytics/about/" target="_blank" rel="noopener noreferrer">Cloudflare Web Analytics</a> for aggregate page visits and loading performance. Its script sends page and referring addresses with query strings and fragments removed, browser information and performance measurements to Cloudflare. Requests also expose ordinary connection information to the service. Cloudflare does not use tracking cookies or a persistent visitor identifier for this service. Page visits are not a count of unique people, and some automated traffic may remain.</p>
  <p>Check <em>Exclude my visits</em> to stop future analytics requests from this browser. If analytics has already loaded, the page reloads to remove its listeners; requests already sent cannot be withdrawn. The saved choice applies across tabs on this site. Uncheck to permit measurement on your next navigation; the settings change itself does not load analytics. Set this separately in each browser or profile; clearing site storage clears the choice. If the choice cannot be saved or read, requests are blocked in the current page, but the choice may not survive a reload. Local copies, preview hosts, embedded pages and recognized automated test browsers are excluded. With JavaScript off, no counts are sent.</p>
  <label class="analytics-choice"><input type="checkbox" data-analytics-exclude aria-describedby="analyticsPreferenceStatus" disabled> Exclude my visits</label>
  <p id="analyticsPreferenceStatus" data-analytics-status role="status">This choice is available when JavaScript is on. No counts are sent with JavaScript off.</p>`
};
