/* Informational page shared by the reader and static build; not an article. */
window.LEDGER_PRIVACY = {
  title: "Privacy at The Ledger",
  standfirst: "What this site stores, which services receive requests, and the choices available to you.",
  html: `<h2>On your device</h2>
  <p>Saved stories, reading preferences and the choice to exclude your visits from analytics are stored in this browser. The offline reader caches pages, images and some audio on your device. You can remove this data through your browser's site-data controls; doing so also removes saved stories and privacy choices. These settings do not automatically carry over to other browsers or profiles.</p>
  <h2>Optional speech</h2>
  <p>If you enter your own OpenAI API key in Settings, it is stored locally. When you choose authenticated OpenAI speech, the key and the text being read are sent to OpenAI to generate audio. The analytics integration does not send this key. Without a key, Listen uses the browser or device voice; whether that voice runs locally or uses the vendor's service depends on the browser and voice selected.</p>
  <h2>Requests needed to use the site</h2>
  <p>GitHub Pages hosts The Ledger. Your browser requests the site's pages and gathered Newsstand edition, fonts from Google Fonts, and any images carried by a story from the publisher or image host. If the gathered edition is unavailable, public feed requests can pass through allorigins.win, corsproxy.io or codetabs.com; those services see the requested feed addresses. Opening a source link takes you to that publisher. Services receiving a request can see ordinary connection information, such as your IP address, browser information and the requested address, under their own policies.</p>
  <h2>Aggregate analytics and your choice</h2>
  <p>The canonical public site uses <a href="https://developers.cloudflare.com/web-analytics/about/" target="_blank" rel="noopener noreferrer">Cloudflare Web Analytics</a> for page visits and loading performance. Its script sends page and referring addresses with query strings and fragments removed, browser information and performance measurements to Cloudflare. The service also receives ordinary connection information. Cloudflare does not use tracking cookies or a persistent visitor identifier for this service. Page visits are not unique people, and automated traffic may remain.</p>
  <p>Check <em>Exclude my visits</em> to block future analytics requests in this browser. If analytics has already loaded, the page reloads to remove its listeners. The saved choice applies across tabs on this site. Uncheck to permit measurement on the next navigation. Requests already sent cannot be withdrawn. If the choice cannot be saved or read, counting is blocked in the current page, but the choice may not survive a reload. Local copies, preview hosts and recognized automated test browsers are excluded; JavaScript-off pages send no analytics.</p>
  <label class="analytics-choice"><input type="checkbox" data-analytics-exclude aria-describedby="analyticsPreferenceStatus" disabled> Exclude my visits</label>
  <p id="analyticsPreferenceStatus" data-analytics-status role="status">This choice is available when JavaScript is on. No counts are sent with JavaScript off.</p>
  <h2>Advertising: currently disabled</h2>
  <p>Advertising is currently disabled. The Google AdSense application is under review; The Ledger does not currently load Google advertising or consent-message scripts.</p>
  <p>If advertising is enabled later, Google and selected advertising partners may use cookies or similar identifiers for ad delivery, measurement and personalization. Advertising cookies can support ads based on earlier visits to this site or other sites. Available choices and partner information will need to match the actual advertising and consent-message configuration before launch.</p>
  <p>Read <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer">how Google uses information from partner sites</a> and <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google's Privacy Policy</a>. <a href="https://www.google.com/settings/ads" target="_blank" rel="noopener noreferrer">Google Ads Settings</a> offers controls for personalized advertising. If other advertising vendors are used, their identities, policies and available opt-out links will be disclosed. Turning off personalization does not necessarily stop all advertising cookies or other ad-related processing.</p>
  <p>A separate <em>Privacy and cookie settings</em> button will appear in the footer or menu only when Google's advertising-choice API is available. It requests Google's European-regulations consent message, when applicable, so you can revisit your choices; its presence does not mean you have consented or that a change succeeded. It does not control Cloudflare analytics. This privacy page can be read without giving advertising consent.</p>
  <h2>Contact</h2>
  <p>For a general privacy question, use the <a href="https://github.com/readtheledger/readtheledger.github.io/issues" target="_blank" rel="noopener noreferrer">public GitHub issue tracker</a>. Posts there are public: do not include API keys, private account details or other sensitive information. No confidential privacy-contact channel is currently listed.</p>`
};
